apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
spec:
  containers:
  - image: mysql
    name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
    env:
     - name: MYSQL_ROOT_PASSWORD
       value: password
     - name: MYSQL_DATABASE
       value: eazytaining
     - name: MYSQL_USER
       value: eazy
     - name: MYSQL_PASSWORD
       value: easy
  volumes:
  - name: mysql-data
    hostPath:
    #chemin du dossier sur l'hote
      path: /data
    #ce  chemin est optionel
      type: Directory
